### ISSUE TITLE
просьба проверить тестовое задание

### ISSUE THREAD

**Issue by bmarvinb** [bmarvinb/wysiwig#1]

**Comment by JSMonk** [comment]
1. При копировании и вставке в Microsoft Office Online - пропадают стили.
<img width="587" alt="Screen Shot 2021-01-07 at 1 35 08 PM" src="https://user-images.githubusercontent.com/10776615/103888358-47fa7680-50ed-11eb-83de-04165371f866.png">
<img width="261" alt="Screen Shot 2021-01-07 at 1 35 14 PM" src="https://user-images.githubusercontent.com/10776615/103888364-4a5cd080-50ed-11eb-91de-1b9f21710e06.png">

**Comment by bmarvinb** [comment]
> 1. При копировании и вставке в Microsoft Office Online - пропадают стили.
> 
> <img alt="Screen Shot 2021-01-07 at 1 35 08 PM" width="587" src="https://user-images.githubusercontent.com/10776615/103888358-47fa7680-50ed-11eb-83de-04165371f866.png">
> 
> <img alt="Screen Shot 2021-01-07 at 1 35 14 PM" width="261" src="https://user-images.githubusercontent.com/10776615/103888364-4a5cd080-50ed-11eb-91de-1b9f21710e06.png">

Поправил

**Comment by bmarvinb** [comment]
![image](https://user-images.githubusercontent.com/23120972/103897964-e9d58f80-50fc-11eb-82c1-0253768a9e9c.png)
![image](https://user-images.githubusercontent.com/23120972/103897990-f35ef780-50fc-11eb-9cb5-449654062d23.png)

**Comment by bmarvinb** [comment]
@JSMonk Исправлено, плюс сделал рефакторинг.

**Comment by JSMonk** [comment]
1. При использовании хэдера, последующем использовании CTRL+Z (или CMD+Z) и попытке использовать хэдер еще раз - хэдер не применяется.

https://user-images.githubusercontent.com/10776615/104033032-aa2fa600-51d7-11eb-8eb8-608fdd0159f4.mov

2. При вставке содержимого в Mircosoft Office Online теряется жирность текста и пропадают марджины (попытайтесь использовать стилизацию для хэдеров, италиков и болдов из `styles/editor.css`)
<img width="570" alt="Screen Shot 2021-01-08 at 5 35 49 PM" src="https://user-images.githubusercontent.com/10776615/104033456-3772fa80-51d8-11eb-9ee8-51dda7c2128e.png">
<img width="357" alt="Screen Shot 2021-01-08 at 5 36 07 PM" src="https://user-images.githubusercontent.com/10776615/104033464-39d55480-51d8-11eb-8e4f-39f6b73267d0.png">

**Comment by bmarvinb** [comment]
![image](https://user-images.githubusercontent.com/23120972/104049182-34ced000-51ed-11eb-9eab-7a67d3ee6e2e.png)
![image](https://user-images.githubusercontent.com/23120972/104049210-41ebbf00-51ed-11eb-9ba8-84a48490cc9c.png)
@JSMonk 
Со стилями ситуацию поправил, но все равно не идеально, в MS Word выглядит не так как должно. 
С проблемой Ctrl + z я разобрался
С таким результатом в word не засчитывается?

**Comment by bmarvinb** [comment]
@JSMonk Насколько критична проблема?

**Comment by JSMonk** [comment]
А у Вас проблема только с `font-weight`?

**Comment by bmarvinb** [comment]
@JSMonk 
![image](https://user-images.githubusercontent.com/23120972/104133123-24079100-538a-11eb-98c6-a8b0f8fb601d.png)
![image](https://user-images.githubusercontent.com/23120972/104133149-603af180-538a-11eb-97f5-e0dda4acf349.png)

Похоже что проблема в заголовке, отсутствует нижний отступ

**Comment by JSMonk** [comment]
Ну посмотрите, какая результирующая верстка вставляется. Может натолкнет Вас на решение 😄

**Comment by bmarvinb** [comment]
Uploading Screen Recording 2021-01-10 at 22.27.18.mov…

**Comment by bmarvinb** [comment]
@JSMonk 
Я записал видео обычного редактирования текста в ворде, и там такая же ситуация, возможно это вовсе не ошибка тогда?

**Comment by bmarvinb** [comment]
https://user-images.githubusercontent.com/23120972/104134585-3639fd00-5393-11eb-9eda-f71da6e89305.mov

**Comment by bmarvinb** [comment]
Вот видео с тем как работает когда я вставляю текст из своего редактора

https://user-images.githubusercontent.com/23120972/104134618-7ef1b600-5393-11eb-9d15-d245e276f87b.mov

**Comment by JSMonk** [comment]
Ну вот теперь все так. Сегодня проверю (ближе к вечеру)

**Comment by JSMonk** [comment]
1. При выделении слова и клике на хэдер - вся строка становиться хэдером.

https://user-images.githubusercontent.com/10776615/104200366-3c7eb680-5431-11eb-9b9d-2b42d3aea685.mov

**Comment by bmarvinb** [comment]
Пробовал несколько вариантов как такого добиться, идея была в том что бы заворачивать каждое слово в спан, и на него стили уже вешать, а не тегом все заворачивать, но тогда это ломает ctrl + z, проверял.

Еще идея каждую команду хранить, что бы можно было понимать в любой момент времени какая до нее, но уверен вылезут другие проблемы, с которыми нужно дополнительно разбираться. 
К сожалению это лучшее что могу сейчас сделать, если не закапываться дальше на много часов.
Задача интересная, никогда подобного не реализовывал, было интересно. 

Сейчас много задач вне работы, и не могу много времени тратить до 28 января, обычно делаю задачи до конца, но тут есть свои причины, и приоритеты.

**Comment by JSMonk** [comment]
1. Ну, сам ctrl+z необязателен (его не было в задании), так что можете на него забить (я просто заметил такое поведение нечаянно). 
Так что Вам бы только поправить выделение всей строки и все 😺

**Comment by bmarvinb** [comment]
https://user-images.githubusercontent.com/23120972/104230601-744c2500-5456-11eb-9322-249d876e8e07.mov

**Comment by bmarvinb** [comment]
@JSMonk 
Благодарю за терпение, кое что поменял, наверное иду в нужную сторону.

**Comment by JSMonk** [comment]
Супер, сегодня посмотрю.

**Comment by bmarvinb** [comment]
@JSMonk не смотрели?

**Comment by JSMonk** [comment]
Здравствуйте, к сожалению не посмотрел вчера, за что прошу прощение.
Только что все проверил, все окей, только комбинация стилей сломалась:

https://user-images.githubusercontent.com/10776615/104442564-e9764200-559d-11eb-9991-a39bbca463c9.mov

Сможете поправить?

**Comment by bmarvinb** [comment]
Думаю могу

**Comment by bmarvinb** [comment]
@JSMonk 
Я пофиксил это, но это скорее костыль, но эту проблему решает, остальное не ломает.

**Comment by JSMonk** [comment]
Да, все работает.
Задание зачтено.
Хорошая работа 👍

**Comment by bmarvinb** [comment]
@JSMonk спасибо, какие шаги дальше, ждать приглашения ?

**Comment by xanf** [comment]
@bmarvinb Можно вашу почту (если подписаны были на Patreon - то ту же что и на патреоне) и telegram-контакт (номер или ник, все-равно) для дублирования сообщений.

Пройдет некоторое количество времени (мы сдвинем старт на неделю вперед) и вы получите ссылку на оплату и я сообщу вам дальнейшие шаги

**Comment by bmarvinb** [comment]
@xanf mdmitry94@gmail.com, +380665862301
